name = "GRAPELinesearchAnalysis"
uuid = "290eba36-e2d8-4488-81b6-f66cc44f2186"
authors = ["Michael Goerz <mail@michaelgoerz.net>"]
version = "0.8.0+dev"

[deps]
GRAPE = "6b52fcaf-80fe-489a-93e9-9f92080510be"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
GRAPE = "~1.2"
LinearAlgebra = "1"
Plots = "1.40"
Printf = "1"
julia = "1.10"
